# Generated by Django 4.1.5 on 2023-01-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="titel",
            new_name="title",
        ),
    ]
