# Generated by Django 4.1.5 on 2023-01-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_rename_titel_review_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
